### ISSUE TITLE
你好，这个问一下上传文件怎么没有成功呢

### ISSUE THREAD

**Issue by blackstar24** [FunnyWolf/DarkGuardian#1]
windows7 登陆windows server 2012，但是在Windows7 启动项中发现上传的指定文件。配置文件conf.json中的upload_file_list 如下写的
  "upload_file_list": [
    "C:\\Users\\test\\Desktop\\release\\test.zip"
  ]

**Comment by FunnyWolf** [comment]
> windows7 登陆windows server 2012，但是在Windows7 启动项中发现上传的指定文件。配置文件conf.json中的upload_file_list 如下写的
> "upload_file_list": [
> "C:\Users\test\Desktop\release\test.zip"
> ]

你好,这个功能目的就是将木马上传到管理人员机器的启动项中,另外upload_file_list只填写文件名就可以,将zip文件放在exe的相同文件夹下.

**Comment by blackstar24** [comment]
这个我也试过了也是不行啊。就是放在exe相同目录下

**Comment by blackstar24** [comment]
> > windows7 登陆windows server 2012，但是在Windows7 启动项中发现上传的指定文件。配置文件conf.json中的upload_file_list 如下写的
> > "upload_file_list": [
> > "C:\Users\test\Desktop\release\test.zip"
> > ]
> 
> 你好,这个功能目的就是将木马上传到管理人员机器的启动项中,另外upload_file_list只填写文件名就可以,将zip文件放在exe的相同文件夹下.

这个我也试过了也是不行啊。就是放在exe相同目录下，配置里面也是直接写的文件名

**Comment by blackstar24** [comment]
> > > windows7 登陆windows server 2012，但是在Windows7 启动项中发现上传的指定文件。配置文件conf.json中的upload_file_list 如下写的
> > > "upload_file_list": [
> > > "C:\Users\test\Desktop\release\test.zip"
> > > ]
> > 
> > 
> > 你好,这个功能目的就是将木马上传到管理人员机器的启动项中,另外upload_file_list只填写文件名就可以,将zip文件放在exe的相同文件夹下.
> 
> 这个我也试过了也是不行啊。就是放在exe相同目录下，配置里面也是直接写的文件名

我是在启动项里没有发现文件

> > windows7 登陆windows server 2012，但是在Windows7 启动项中发现上传的指定文件。配置文件conf.json中的upload_file_list 如下写的
> > "upload_file_list": [
> > "C:\Users\test\Desktop\release\test.zip"
> > ]
> 
> 你好,这个功能目的就是将木马上传到管理人员机器的启动项中,另外upload_file_list只填写文件名就可以,将zip文件放在exe的相同文件夹下.

不好意思我上面表达错了，是没有在启动项发现文件。我也试过放在exe相同目录下，配置里面也是直接写的文件名，但是还是没有发现文件

**Comment by FunnyWolf** [comment]
> > > > windows7 登陆windows server 2012，但是在Windows7 启动项中发现上传的指定文件。配置文件conf.json中的upload_file_list 如下写的
> > > > "upload_file_list": [
> > > > "C:\Users\test\Desktop\release\test.zip"
> > > > ]
> > > 
> > > 
> > > 你好,这个功能目的就是将木马上传到管理人员机器的启动项中,另外upload_file_list只填写文件名就可以,将zip文件放在exe的相同文件夹下.
> > 
> > 
> > 这个我也试过了也是不行啊。就是放在exe相同目录下，配置里面也是直接写的文件名
> 
> 我是在启动项里没有发现文件
> 
> > > windows7 登陆windows server 2012，但是在Windows7 启动项中发现上传的指定文件。配置文件conf.json中的upload_file_list 如下写的
> > > "upload_file_list": [
> > > "C:\Users\test\Desktop\release\test.zip"
> > > ]
> > 
> > 
> > 你好,这个功能目的就是将木马上传到管理人员机器的启动项中,另外upload_file_list只填写文件名就可以,将zip文件放在exe的相同文件夹下.
> 
> 不好意思我上面表达错了，是没有在启动项发现文件。我也试过放在exe相同目录下，配置里面也是直接写的文件名，但是还是没有发现文件

将exe直接打包成zip文件后,放在主程序的相同目录(win2012上),这时使用windows7登录win2012后,等待2分钟,就可以在windows7的启动文件夹下看到压缩成zip的exe了

**Comment by blackstar24** [comment]
> > > > > windows7 登陆windows server 2012，但是在Windows7 启动项中发现上传的指定文件。配置文件conf.json中的upload_file_list 如下写的
> > > > > "upload_file_list": [
> > > > > "C:\Users\test\Desktop\release\test.zip"
> > > > > ]
> > > > 
> > > > 
> > > > 你好,这个功能目的就是将木马上传到管理人员机器的启动项中,另外upload_file_list只填写文件名就可以,将zip文件放在exe的相同文件夹下.
> > > 
> > > 
> > > 这个我也试过了也是不行啊。就是放在exe相同目录下，配置里面也是直接写的文件名
> > 
> > 
> > 我是在启动项里没有发现文件
> > > > windows7 登陆windows server 2012，但是在Windows7 启动项中发现上传的指定文件。配置文件conf.json中的upload_file_list 如下写的
> > > > "upload_file_list": [
> > > > "C:\Users\test\Desktop\release\test.zip"
> > > > ]
> > > 
> > > 
> > > 你好,这个功能目的就是将木马上传到管理人员机器的启动项中,另外upload_file_list只填写文件名就可以,将zip文件放在exe的相同文件夹下.
> > 
> > 
> > 不好意思我上面表达错了，是没有在启动项发现文件。我也试过放在exe相同目录下，配置里面也是直接写的文件名，但是还是没有发现文件
> 
> 将exe直接打包成zip文件后,放在主程序的相同目录(win2012上),这时使用windows7登录win2012后,等待2分钟,就可以在windows7的启动文件夹下看到压缩成zip的exe了

谢谢解答哈
